transitions:
  - [LMC::Initial_, OK, LMC::ConfigManip_, Auto]

states:
  LMC::Initial_:
    base: LMC::Initial
    configs:
      autoStartTime: 2.0

  LMC::ConfigManip_:
    base: LMC::ConfigManip
    configs:
      preUpdateObj: true
      preWalk: true
      waypointList:
        - startTime: 2.0
          duration: 30.0
          relPose:
            translation: [1.2, -1.2, 0.0]
            rotation: [0.0, 0.0, -1.5708]

ManipManager:
  objPoseTopic: /cnoid/object/pose
  objVelTopic: /cnoid/object/vel
